#!/usr/bin/bash
if [ "`id -u`" -ne 0 ]; then
 echo "Switching from `id -un` to root"
 exec sudo "$0"
 exit 99
fi

echo "unbind"
echo -n "i8042" > /sys/bus/platform/drivers/i8042/unbind
echo "bind"
echo -n "i8042" > /sys/bus/platform/drivers/i8042/bind
echo "finish"
